name: build-and-publish-module

on:
  push:
    tags:
      - "v**"

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Extract version from tag
        id: version
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".TrimStart("v")
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

  publish:
    needs: version
    uses: AzooSystems/AzooBuilder/.github/workflows/build-and-release-ps-module.yml@3b2cbf36eba6b6dd16be58c6ba38617ab3256a52
    with:
      version: ${{ needs.version.outputs.version }}
      moduleName: AzooEmptyModuleForTesting
      modulePath: ./src/AzooEmptyModuleForTesting
      publishToGitHubPackagesNuGetFeed: true
      gitHubPackagesNuGetFeedOrganizationName: AzooSystems
      gitHubPackagesNuGetFeedRepositoryName: GitHub
      gitHubPackagesNuGetFeedUri: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      publishToPowerShellGallery: true
      psGalleryRepositoryName: PSGallery
      publishToGitHubRelease: true

    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      galleryApiKey: ${{ secrets.GALLERY_API_KEY }}
      gitHubReleaseToken: ${{ secrets.GITHUB_TOKEN }}
